frota/urls.py
"""frota URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:


Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from frota.veiculos import views
from frota.core import views
from frota.veiculos import urls as veiculos_urls

urlpatterns = [
    url(r'^$',views.index),
    url(r'^veiculos/', include(veiculos_urls, namespace='veiculos')),
    url('admin/', admin.site.urls)]

if settings.DEBUG:
   urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frota/veiculos/urls.py
from django.conf.urls import url
from frota.veiculos import views


app_name='veiculos'

urlpatterns = [
    url(r'^lista-departamento/$',views.lista_departamento, name='lista-departamentos'),
    url(r'^lista-responsaveis/$',views.lista_responsaveis, name='lista-responsaveis'),
    #url(r'^deleta-departamento/(?P<id_departamento>[0-9]+)/$',views.deleta_departamento, name='deleta_departamento'),
    url(r'^deleta-departamento/(?P<id_departamento>)/$',views.deleta_departamento, name='deleta_departamento'),
    url(r'^novo-responsavel/$',views.novo_responsavel, name='novo-responsavel'),
    url(r'^novo-departamento/$',views.novo_departamento, name='novo-departamento'),
]

frota/veiculos/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class departamento(models.Model):
    nome = models.CharField(u'Nome do Departamento', max_length=30, blank=True)
    centrocusto = models.CharField(u'Centro de Custo', max_length=10, blank=True)

    def __str__(self):
        return self.nome

class responsavel(models.Model):

    PRIORIDADE_CHOICES = (
        ('U','Usuario'),       #Somente responsavel pelo Veiculo
        ('M','Profissional'),   #Qualquer Usuario do cadastro
        ('P','Profissional Especializado'),           #Apenas profissionais habilitados
            )
    PRIORIDADE_CHOICES_CNH = (
        ('A','A - Moto'),      
        ('B','B - Carro'),   
        ('C','C - Veiculo de carga acima 3,5 Ton'), 
        ('D','D - Veiculo de Passageiros acima de 8 Lugares'), 
        ('E','E - Veiculo com unidade acoplada acima de 6 Ton'), 
            )

    nome         = models.CharField(u'Nome do Responsável', max_length=30)
    departamento = models.ForeignKey(departamento, verbose_name='Departamento', on_delete=models.CASCADE)
    tipo = models.CharField(u'Tipo', max_length=1, choices=PRIORIDADE_CHOICES)
    cnhcat = models.CharField(u'Categoria CNH ', max_length=2, choices=PRIORIDADE_CHOICES_CNH)
    
    email        = models.CharField(u'E-mail', max_length=30)
    telefone     = models.CharField(u'Telefone Contato', max_length=15)
    cnh          = models.FileField(upload_to="media/", blank=True)
    aut          = models.FileField(upload_to="media/", blank=True)
      
    def __str__(self):
          return self.nome


class veiculo(models.Model):
    PRIORIDADE_CHOICES = (
            ('E','Exclusivo'),       #Somente responsavel pelo Veiculo
            ('C','Compartilhado'),   #Qualquer Usuario do cadastro
            ('F','Frota'),           #Apenas profissionais habilitados
            ('R','Restrito'),        #Apenas profissionais habilitados especializados 
        )
        
    placa = models.CharField(u'Placa', max_length=8)
    tipo = models.CharField(u'Tipo', max_length=1, choices=PRIORIDADE_CHOICES)
    marcamodelo  = models.CharField(u'Marca/Modelo', max_length=40)
    apelido  = models.CharField(u'Apelido', max_length=20)
    Ano  = models.IntegerField(u'Ano Fabricação')
    modelo  = models.IntegerField(u'Modelo Fabricação')
    cor  = models.CharField(u'Cor', max_length=15)
    combustivel  = models.CharField(u'Combustível', max_length=30)
    cidade  = models.CharField(u'Cidade', max_length=15)
    responsavel  = models.ForeignKey(responsavel, verbose_name='Responsável', on_delete=models.CASCADE)
    Odometro  = models.IntegerField(u'Odômetro')

    def __str__(self):
            return self.apelido

class combustivel(models.Model):
      descricao = models.CharField(u'Nome do Combustivel', max_length=30)

      def __str__(self):
            return self.descricao
class posto(models.Model):
    Descricao = models.CharField(u'Nome do Posto', max_length=50)

    def __str__(self):
            return self.Descricao

class tabelacombustivel(models.Model):
    #posto = models.IntegerField(u'Código posto')
    #combustivel = models.IntegerField(u'Combustível')
    #valor = models.DecimalField(u'Valor', max_digits=5, decimal_places=4)
    posto  = models.ForeignKey(posto, verbose_name='Posto', on_delete=models.CASCADE)
    combustivel  = models.ForeignKey(combustivel, verbose_name='Combustivel', on_delete=models.CASCADE)
    valor = models.DecimalField(u'Valor', max_digits=5, decimal_places=4)
    
class manutencao(models.Model):
    Descricao = models.CharField(u'Nome da manutenção', max_length=50)

    def __str__(self):
            return self.Descricao

class empresa(models.Model):
    PRIORIDADE_CHOICES = (
        ('FAEF','FAEF'),
        ('FAIP','FAIP'),
        ('FAIT','FAIT'),
        ('EDUVALES','EDUVALES'),
    )
    fantasia = models.CharField(u'Fantasia', max_length=10, choices=PRIORIDADE_CHOICES)
    nome = models.CharField(u'Nome da Empresa', max_length=50)
    cnpj = models.CharField(u'CNPJ', max_length=14)

    def __str__(self):
            return self.fantasia

class requisicao(models.Model):
    PRIORIDADE_CHOICES = (
        ('TC','Completar'),
        ('LT','Litros'),
        ('LG','Litros no Galão'),
        ('LP','Litros Veiculo Professor'),
    )
    data = models.DateTimeField(default=datetime.now())
    empresa  = models.ForeignKey(empresa, verbose_name='empresa', on_delete=models.CASCADE)
    responsavel = models.ForeignKey(responsavel, verbose_name='Responsavel Abastecimento', on_delete=models.CASCADE)
    veiculo = models.ForeignKey(veiculo, verbose_name='Veiculo', on_delete=models.CASCADE)
    km = models.IntegerField(u'KM atual')
    posto = models.ForeignKey(posto, verbose_name='posto', on_delete=models.CASCADE)
    combustivel = models.ForeignKey(combustivel, verbose_name='Combustível', on_delete=models.CASCADE)
    quantidade = models.IntegerField(u'Quantidade', blank=True)
    tipoabastecimento = models.CharField(u'Tipo Abastecimento', max_length=2, choices=PRIORIDADE_CHOICES)

'''
class Album(TimeStampedModel):
    title = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    cover_photo = models.ForeignKey('Photo', related_name='+', blank=True,
                                    null=True)
    is_public = models.BooleanField(default=True)
    date_added = models.DateField(null=True, blank=True)
    tags = TaggableManager(blank=True, help_text=None)
    order = models.PositiveIntegerField(default=9999)

# exemplo Galeria em massa arrastar

class Photo(TimeStampedModel):
    album = models.ForeignKey(Album)
    file = models.ImageField(upload_to=upload_to)
    description = models.TextField(blank=True, null=True)
    is_public = models.BooleanField(default=True)
    tags = TaggableManager(blank=True, help_text=None)

'''

frota/veiculos/forms.py
from django.forms.widgets import ClearableFileInput
from django import forms
from .models import departamento,responsavel,veiculo,combustivel,posto,tabelacombustivel,manutencao, empresa, requisicao

class departamentoForm(forms.ModelForm):
    Nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    centrocusto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
          model = departamento
          fields = '__all__'
          widgets= {
                   'nome':forms.TextInput(attrs={
                   'class':'form-control', 
                   'maxlength': 255, 
                   'placeholder': 'Digite o Departamento'
                 })}

class responsavelForm(forms.ModelForm):
    cnh = forms.ImageField(widget=ClearableFileInput, required=False)
    aut = forms.ImageField(widget=ClearableFileInput, required=False)

    class Meta:
        model = responsavel
        fields = '__all__'
        widgets= {
                   'nome':forms.TextInput(attrs={
                   'class':'form-control', 
                   'maxlength': 255, 
                   'placeholder': 'Digite o nome do Usuário'
                 })}
                 
class veiculos(forms.ModelForm):
    class Meta:
          model = departamento
          fields = '__all__'

frota/veiculos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import departamentoForm,responsavelForm
from .models import responsavel, departamento
#,veiculoForm,combustivelForm,postoForm,tabelacombustivelForm,manutencaoForm, empresaForm, requisicaoForForm


# Create your views here.
#def novo_departamento(request):
#    if request.method == 'POST':
#       form = departamentoForm(request.POST)
#       if form.is_valid():
#           form.save()
#           #return redirect('veiculos/novo_departamento.html')
#           return redirect('veiculos:novo-departamento')
#       else:
#           print(form.errors)
#    else:
#        form = departamentoForm()
#    return render(request, 'veiculos/novo_departamento.html', {'form':form})

def novo_departamento(request):
    if request.method == 'POST':
       #return redirect('veiculos:novo-responsavel')
       form = departamentoForm(request.POST)
       if form.is_valid():
          form.save()
       else:
           print(form.errors)
    else:
#        return HttpResponse('Responsavel adcionado com Sucesso!!!')
        form = departamentoForm()
    return render(request, 'veiculos/novo_departamento.html', {'form':form})

def novo_responsavel(request):
    if request.method == 'POST':
       form = responsavelForm(request.POST, request.FILES)
       if form.is_valid():
           form.save()
           #return HttpResponse('Responsavel adcionado com Sucesso!!!')
           return redirect('veiculos:novo-responsavel')
       else:
           print(form.errors)
    else:
        form = responsavelForm()
    return render(request, 'veiculos/novo_responsavel.html', {'form':form})

def lista_departamento(request):
    departamentos=departamento.objects.all()
    orm = departamento.objects.all()
    return render(request, 'veiculos/lista_departamento.html',{'deptos':orm})


def lista_responsaveis(request):
    usuarioveic = responsavel.objects.all()
    return render(request, 'veiculos/lista_responsaveis.html',{'colaborador':usuarioveic})


def deleta_departamento(request, id_departamento):
    departamentos = departamento.objects.get(id=id_departamento).delete()
    return render(request, 'veiculos/lista_departamento.html',{'deptos':departamentos})
    #return redirect('veiculos/lista_departamentos.html' )







# exemplo uppload
'''
from django.views.generic import View

from braces.views import (
    AjaxResponseMixin,
    JSONResponseMixin,
    LoginRequiredMixin,
    SuperuserRequiredMixin,
)

from calazanblog.gallery.models import Album, Photo


AjaxPhotoUploadView(LoginRequiredMixin,
                    SuperuserRequiredMixin,
                    JSONResponseMixin,
                    AjaxResponseMixin,
                    View):
    """
    View for uploading photos via AJAX.
    """
    def post_ajax(self, request, *args, **kwargs):
        try:
            album = Album.objects.get(pk=kwargs.get('pk'))
        except Album.DoesNotExist:
            error_dict = {'message': 'Album not found.'}
            return self.render_json_response(error_dict, status=404)

        uploaded_file = request.FILES['file']
        Photo.objects.create(album=album, file=uploaded_file)

        response_dict = {
            'message': 'File uploaded successfully!',
        }

        return self.render_json_response(response_dict, status=200)


'''

frota/veiculos/templates/veiculos/exemploForm.html
<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Password</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>...</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>

frota/veiculos/templates/veiculos/lista_departamento.html
{% extends "base.html"%}
{%block body%}
<div class="row">
 
  <table border="0">
    <thead>
       <tr>
          <th width="1100"><h1>Lista de Departamentos</h1></th>
          <th><a href="{% url 'veiculos:novo-departamento' %}" class="btn btn-primary"> Novo</a></th>
        </tr>
     </thead>
 </table>

  <table class="table">
    <thead>
       <tr>
          <th>Departamento</th>
          <th>Centro de Custo</th>
          <th colspan="2" style="text-align:center">Ações</th>
        </tr>
     </thead>
     <tbody>
        {% for c in deptos%}
           <tr>
              <td  width="900">{{ c.nome}}</td>
              <td  width="150">{{c.centrocusto}}</td>
              <td><a href="{% url 'veiculos:deleta_departamento' c.id %}" class="btn btn-info btn-xs"> Editar</a></td>
              <td><a href="{% url 'veiculos:deleta_departamento' c.id %}" class="btn btn-danger btn-xs"> Excluir</a></td>
           </tr>
        {% endfor %}
     </tbody>
 </table>
</div>
{% endblock body%}

frota/veiculos/templates/veiculos/lista_responsaveis.html
{% extends "base.html"%}
{%block body%}
<div class="row">
  <h1> Lista de Responsáveis</h1>
  <table class="table">
    <thead>
       <tr>
          <th>Nome</th>
          <th>Departamento</th>
          <th>Tipo</th>
          <th>Categoria CNH</th>
          <!--
          <th>Email</th>
          <th>Telefone</th>
          <th>CNH</th>
          <th>AUT</th>
          -->
        <th><a href="{% url 'veiculos:novo-responsavel' %}" class="btn btn-primary"> Novo</a></th>
        </tr>

     </thead>
     <tbody>
        {% for d in colaborador%}
           <tr>
              <td>{{ d.nome}} </td>
              <td>{{ d.departamento}}</td>
              <td>{{ d.get_tipo_display}}</td>
              <td>{{ d.get_cnhcat_display}}</td>
          <!--
              <td>{{ d.email}}</td>
              <td>{{ d.telefone}}</td>
              <td>{{ d.cnh}}</td>
              <td>{{ d.aut}}</td>
            -->
           </tr>
        {% endfor %}
     </tbody>
 </table>
 <a href="{% url 'veiculos:novo-responsavel' %}" class="btn"> Novo</a>
</div>
{% endblock body%}

frota/veiculos/templates/veiculos/novo_departamento.html
{% extends "base.html"%}
{% load widget_tweaks %}
{%block body%}
<br>
  <form class="" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <h1>Cadastro de Departamentos</h1>
   <div class="cadastros-group" border:solid 1px>
    
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="{{form.nome.id_for_label}}">Nome</label>
            {{form.nome|add_class:"form-control"}}
         </div>
    </div>
    
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="{{form.centrocusto.id_for_label}}">Centro de Custo</label>
            {{form.centrocusto|add_class:"form-control"}}
         </div>
      </div>

   <button type="submit" class="btn btn-primary">Salvar</button>
   </div>
   <br>
</form>
{% endblock body%}

frota/veiculos/templates/veiculos/novo_responsavel.html
{% extends "base.html"%}
{% load widget_tweaks %}
{%block body%}
  <form class="" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <h1>Cadastro de Autorizados</h1>
   <div class="cadastros-group" border:solid 1px>

      <div class="form-row">
        <div class="form-group col-md-12">
            <label for="{{form.nome.id_for_label}}">Nome</label>
            {{form.nome|add_class:"form-control"}}
         </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <label for="{{form.departamento.id_for_label}}">Departamento</label>
          {{form.departamento|add_class:"form-control"}}
        </div>

        <div class="form-group col-md-4">
          <label for="{{form.departamento.id_for_label}}">Tipo</label>
          {{form.tipo|add_class:"form-control"}}
        </div>

        <div class="form-group col-md-4">
            <label for="{{form.departamento.id_for_label}}">CNH Categoria</label>
            {{form.cnhcat|add_class:"form-control"}}
        </div>

        <div class="form-group col-md-6">
            <label for="{{form.departamento.id_for_label}}">E-Mail</label>
            {{form.email|add_class:"form-control"}}
        </div>

        <div class="form-group col-md-6">
           <label for="{{form.departamento.id_for_label}}">Telenone</label>
           {{form.telefone|add_class:"form-control"}}
        </div>

        <div class="form-group col-md-6">
           <label for="{{form.cnh.id_for_label}}">CNH</label>
           {{form.cnh|add_class:"form-control"}}
        </div>

        <div class="form-group col-md-6">
           <label for="{{form.aut.id_for_label}}">Autorização</label>
           {{form.aut|add_class:"form-control"}}
        </div>


      </div>
     </div>

  <div class="form-group col-md-12">
     <button type="submit" class="btn btn-primary">Salvar</button>
  </div>
 </div>
 <br>
</form>
{% endblock body%}