frota/urls.py
"""frota URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:


Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from frota.veiculos import views
from frota.core import views
from frota.veiculos import urls as veiculos_urls

urlpatterns = [
    url(r'^$',views.index),
    url(r'^veiculos/', include(veiculos_urls, namespace='veiculos')),
    url('admin/', admin.site.urls)]

if settings.DEBUG:
   urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frota/veiculos/urls.py
from django.conf.urls import url
from frota.veiculos import views


app_name='veiculos'

urlpatterns = [
    url(r'^lista-departamento/$',views.lista_departamento, name='lista-departamentos'),
    url(r'^lista-responsaveis/$',views.lista_responsaveis, name='lista-responsaveis'),
    #url(r'^deleta-departamento/(?P<id_departamento>[0-9]+)/$',views.deleta_departamento, name='deleta_departamento'),
    url(r'^deleta-departamento/(?P<id_departamento>)/$',views.deleta_departamento, name='deleta_departamento'),
    url(r'^novo-responsavel/$',views.novo_responsavel, name='novo-responsavel'),
    url(r'^novo-departamento/$',views.novo_departamento, name='novo-departamento'),
]

frota/core/models.py
from django.db import models

frota/core/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse



def index(request):
    return render(request, 'base.html')

frota/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Controle de Frota</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static "css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/starter-template.css" %}"  rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static "js/ie8-responsive-file-warning.js" %}"></script><![endif]-->
    <script src="{%static "js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">GERFROTA</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="{%url 'veiculos:lista-departamentos'%}">Departamentos</a></li>
            <li><a href="{%url 'veiculos:lista-responsaveis'%}">Responsáveis</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <br>
  <br>
   <div class="container" style="border:1px solid #cecece;">
    {%block body%}

          <div class="row">
         
          </div> 

    {%endblock body%}
       </div><!-- /.container -->

    


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery.min.js" %}"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>